-- Insert Users
INSERT INTO users (name, email, password) VALUES ('Christopher Wilson', 'christopher.wilson1@service.net', '$2a$10$hashedpasswordhashedpasswordhashedpasswordhashedpassw');
INSERT INTO users (name, email, password) VALUES ('Matthew Hernandez', 'matthew.hernandez2@platform.dev', '$2a$10$hashedpasswordhashedpasswordhashedpasswordhashedpassw');
INSERT INTO users (name, email, password) VALUES ('Ryan Davis', 'ryan.davis3@example.com', '$2a$10$hashedpasswordhashedpasswordhashedpasswordhashedpassw');
INSERT INTO users (name, email, password) VALUES ('Jennifer White', 'jennifer.white4@cloud.systems', '$2a$10$hashedpasswordhashedpasswordhashedpasswordhashedpassw');
INSERT INTO users (name, email, password) VALUES ('Michael Clark', 'michael.clark5@service.net', '$2a$10$hashedpasswordhashedpasswordhashedpasswordhashedpassw');
INSERT INTO users (name, email, password) VALUES ('William Davis', 'william.davis6@cloud.systems', '$2a$10$hashedpasswordhashedpasswordhashedpasswordhashedpassw');
INSERT INTO users (name, email, password) VALUES ('Barbara Jones', 'barbara.jones7@platform.dev', '$2a$10$hashedpasswordhashedpasswordhashedpasswordhashedpassw');
INSERT INTO users (name, email, password) VALUES ('Brian Williams', 'brian.williams8@platform.dev', '$2a$10$hashedpasswordhashedpasswordhashedpasswordhashedpassw');
INSERT INTO users (name, email, password) VALUES ('Brian Wilson', 'brian.wilson9@service.net', '$2a$10$hashedpasswordhashedpasswordhashedpasswordhashedpassw');
INSERT INTO users (name, email, password) VALUES ('Emily Davis', 'emily.davis10@cloud.systems', '$2a$10$hashedpasswordhashedpasswordhashedpasswordhashedpassw');
INSERT INTO users (name, email, password) VALUES ('Robert Clark', 'robert.clark11@service.net', '$2a$10$hashedpasswordhashedpasswordhashedpasswordhashedpassw');
INSERT INTO users (name, email, password) VALUES ('Elizabeth Lee', 'elizabeth.lee12@platform.dev', '$2a$10$hashedpasswordhashedpasswordhashedpasswordhashedpassw');
INSERT INTO users (name, email, password) VALUES ('Kevin Anderson', 'kevin.anderson13@service.net', '$2a$10$hashedpasswordhashedpasswordhashedpasswordhashedpassw');
INSERT INTO users (name, email, password) VALUES ('Barbara Garcia', 'barbara.garcia14@service.net', '$2a$10$hashedpasswordhashedpasswordhashedpasswordhashedpassw');
INSERT INTO users (name, email, password) VALUES ('Brian Thomas', 'brian.thomas15@example.com', '$2a$10$hashedpasswordhashedpasswordhashedpasswordhashedpassw');
INSERT INTO users (name, email, password) VALUES ('Susan Hernandez', 'susan.hernandez16@app.io', '$2a$10$hashedpasswordhashedpasswordhashedpasswordhashedpassw');
INSERT INTO users (name, email, password) VALUES ('Jennifer Johnson', 'jennifer.johnson17@platform.dev', '$2a$10$hashedpasswordhashedpasswordhashedpasswordhashedpassw');
INSERT INTO users (name, email, password) VALUES ('Patricia Brown', 'patricia.brown18@app.io', '$2a$10$hashedpasswordhashedpasswordhashedpasswordhashedpassw');
INSERT INTO users (name, email, password) VALUES ('Susan Rodriguez', 'susan.rodriguez19@service.net', '$2a$10$hashedpasswordhashedpasswordhashedpasswordhashedpassw');
INSERT INTO users (name, email, password) VALUES ('Brian Martin', 'brian.martin20@app.io', '$2a$10$hashedpasswordhashedpasswordhashedpasswordhashedpassw');
INSERT INTO users (name, email, password) VALUES ('James Garcia', 'james.garcia21@cloud.systems', '$2a$10$hashedpasswordhashedpasswordhashedpasswordhashedpassw');
INSERT INTO users (name, email, password) VALUES ('Susan Hernandez', 'susan.hernandez22@service.net', '$2a$10$hashedpasswordhashedpasswordhashedpasswordhashedpassw');
INSERT INTO users (name, email, password) VALUES ('Linda Miller', 'linda.miller23@cloud.systems', '$2a$10$hashedpasswordhashedpasswordhashedpasswordhashedpassw');
INSERT INTO users (name, email, password) VALUES ('Andrew Harris', 'andrew.harris24@example.com', '$2a$10$hashedpasswordhashedpasswordhashedpasswordhashedpassw');
INSERT INTO users (name, email, password) VALUES ('Barbara Williams', 'barbara.williams25@service.net', '$2a$10$hashedpasswordhashedpasswordhashedpasswordhashedpassw');
INSERT INTO users (name, email, password) VALUES ('Michael Clark', 'michael.clark26@example.com', '$2a$10$hashedpasswordhashedpasswordhashedpasswordhashedpassw');
INSERT INTO users (name, email, password) VALUES ('Daniel Rodriguez', 'daniel.rodriguez27@platform.dev', '$2a$10$hashedpasswordhashedpasswordhashedpasswordhashedpassw');
INSERT INTO users (name, email, password) VALUES ('Mary Hernandez', 'mary.hernandez28@app.io', '$2a$10$hashedpasswordhashedpasswordhashedpasswordhashedpassw');
INSERT INTO users (name, email, password) VALUES ('John White', 'john.white29@service.net', '$2a$10$hashedpasswordhashedpasswordhashedpasswordhashedpassw');
INSERT INTO users (name, email, password) VALUES ('John Hernandez', 'john.hernandez30@app.io', '$2a$10$hashedpasswordhashedpasswordhashedpasswordhashedpassw');
INSERT INTO users (name, email, password) VALUES ('James Rodriguez', 'james.rodriguez31@app.io', '$2a$10$hashedpasswordhashedpasswordhashedpasswordhashedpassw');
INSERT INTO users (name, email, password) VALUES ('Sarah Rodriguez', 'sarah.rodriguez32@example.com', '$2a$10$hashedpasswordhashedpasswordhashedpasswordhashedpassw');
INSERT INTO users (name, email, password) VALUES ('Lisa Martinez', 'lisa.martinez33@cloud.systems', '$2a$10$hashedpasswordhashedpasswordhashedpasswordhashedpassw');
INSERT INTO users (name, email, password) VALUES ('William Lee', 'william.lee34@cloud.systems', '$2a$10$hashedpasswordhashedpasswordhashedpasswordhashedpassw');
INSERT INTO users (name, email, password) VALUES ('James Wilson', 'james.wilson35@example.com', '$2a$10$hashedpasswordhashedpasswordhashedpasswordhashedpassw');
INSERT INTO users (name, email, password) VALUES ('Patricia Thomas', 'patricia.thomas36@platform.dev', '$2a$10$hashedpasswordhashedpasswordhashedpasswordhashedpassw');
INSERT INTO users (name, email, password) VALUES ('Mary Miller', 'mary.miller37@platform.dev', '$2a$10$hashedpasswordhashedpasswordhashedpasswordhashedpassw');
INSERT INTO users (name, email, password) VALUES ('Mary Lopez', 'mary.lopez38@service.net', '$2a$10$hashedpasswordhashedpasswordhashedpasswordhashedpassw');
INSERT INTO users (name, email, password) VALUES ('Sarah Lopez', 'sarah.lopez39@service.net', '$2a$10$hashedpasswordhashedpasswordhashedpasswordhashedpassw');
INSERT INTO users (name, email, password) VALUES ('James White', 'james.white40@platform.dev', '$2a$10$hashedpasswordhashedpasswordhashedpasswordhashedpassw');
INSERT INTO users (name, email, password) VALUES ('Emily Miller', 'emily.miller41@service.net', '$2a$10$hashedpasswordhashedpasswordhashedpasswordhashedpassw');
INSERT INTO users (name, email, password) VALUES ('Lisa Davis', 'lisa.davis42@app.io', '$2a$10$hashedpasswordhashedpasswordhashedpasswordhashedpassw');
INSERT INTO users (name, email, password) VALUES ('Lisa Davis', 'lisa.davis43@example.com', '$2a$10$hashedpasswordhashedpasswordhashedpasswordhashedpassw');
INSERT INTO users (name, email, password) VALUES ('Sarah Rodriguez', 'sarah.rodriguez44@example.com', '$2a$10$hashedpasswordhashedpasswordhashedpasswordhashedpassw');
INSERT INTO users (name, email, password) VALUES ('Michael Lee', 'michael.lee45@example.com', '$2a$10$hashedpasswordhashedpasswordhashedpasswordhashedpassw');
INSERT INTO users (name, email, password) VALUES ('Brian White', 'brian.white46@cloud.systems', '$2a$10$hashedpasswordhashedpasswordhashedpasswordhashedpassw');
INSERT INTO users (name, email, password) VALUES ('John Davis', 'john.davis47@platform.dev', '$2a$10$hashedpasswordhashedpasswordhashedpasswordhashedpassw');
INSERT INTO users (name, email, password) VALUES ('John Johnson', 'john.johnson48@cloud.systems', '$2a$10$hashedpasswordhashedpasswordhashedpasswordhashedpassw');
INSERT INTO users (name, email, password) VALUES ('Matthew Gonzalez', 'matthew.gonzalez49@platform.dev', '$2a$10$hashedpasswordhashedpasswordhashedpasswordhashedpassw');
INSERT INTO users (name, email, password) VALUES ('Sarah Gonzalez', 'sarah.gonzalez50@service.net', '$2a$10$hashedpasswordhashedpasswordhashedpasswordhashedpassw');

-- Insert AppTeams
INSERT INTO appteams (name, description) VALUES ('Data Team 1', 'Team responsible for .NET development and infrastructure');
INSERT INTO appteams (name, description) VALUES ('DevOps Team 2', 'Team responsible for Ruby development and maintenance');
INSERT INTO appteams (name, description) VALUES ('Backend Team 3', 'Team responsible for Ruby development and features');
INSERT INTO appteams (name, description) VALUES ('Infrastructure Team 4', 'Team responsible for Python development and infrastructure');
INSERT INTO appteams (name, description) VALUES ('Growth Team 5', 'Team responsible for Go development and optimization');
INSERT INTO appteams (name, description) VALUES ('Security Team 6', 'Team responsible for Node.js development and maintenance');
INSERT INTO appteams (name, description) VALUES ('AI/ML Team 7', 'Team responsible for React development and features');
INSERT INTO appteams (name, description) VALUES ('Growth Team 8', 'Team responsible for Go development and infrastructure');
INSERT INTO appteams (name, description) VALUES ('Backend Team 9', 'Team responsible for Go development and infrastructure');
INSERT INTO appteams (name, description) VALUES ('Product Team 10', 'Team responsible for React development and support');
INSERT INTO appteams (name, description) VALUES ('Security Team 11', 'Team responsible for Python development and optimization');
INSERT INTO appteams (name, description) VALUES ('Data Team 12', 'Team responsible for PHP development and support');
INSERT INTO appteams (name, description) VALUES ('Product Team 13', 'Team responsible for Go development and optimization');
INSERT INTO appteams (name, description) VALUES ('DevOps Team 14', 'Team responsible for Ruby development and maintenance');
INSERT INTO appteams (name, description) VALUES ('Infrastructure Team 15', 'Team responsible for Ruby development and features');
INSERT INTO appteams (name, description) VALUES ('Mobile Team 16', 'Team responsible for .NET development and infrastructure');
INSERT INTO appteams (name, description) VALUES ('Frontend Team 17', 'Team responsible for C# development and support');
INSERT INTO appteams (name, description) VALUES ('AI/ML Team 18', 'Team responsible for .NET development and maintenance');
INSERT INTO appteams (name, description) VALUES ('Web Team 19', 'Team responsible for Go development and optimization');
INSERT INTO appteams (name, description) VALUES ('Data Team 20', 'Team responsible for C# development and features');

-- Insert Projects
INSERT INTO projects (name, description, user_id) VALUES ('Automation Project 1', 'Automation system for managing workflows', 4);
INSERT INTO projects (name, description, user_id) VALUES ('Automation Project 2', 'Automation system for managing analytics', 41);
INSERT INTO projects (name, description, user_id) VALUES ('Automation Project 3', 'Automation system for managing customer data', 24);
INSERT INTO projects (name, description, user_id) VALUES ('Analytics Project 4', 'Analytics system for managing transactions', 14);
INSERT INTO projects (name, description, user_id) VALUES ('Analytics Project 5', 'Analytics system for managing business operations', 44);
INSERT INTO projects (name, description, user_id) VALUES ('Integration Project 6', 'Integration system for managing transactions', 39);
INSERT INTO projects (name, description, user_id) VALUES ('ERP Project 7', 'ERP system for managing user engagement', 21);
INSERT INTO projects (name, description, user_id) VALUES ('Automation Project 8', 'Automation system for managing transactions', 45);
INSERT INTO projects (name, description, user_id) VALUES ('Marketplace Project 9', 'Marketplace system for managing workflows', 13);
INSERT INTO projects (name, description, user_id) VALUES ('Monitoring Project 10', 'Monitoring system for managing customer data', 9);
INSERT INTO projects (name, description, user_id) VALUES ('Messaging Project 11', 'Messaging system for managing analytics', 11);
INSERT INTO projects (name, description, user_id) VALUES ('Analytics Project 12', 'Analytics system for managing analytics', 35);
INSERT INTO projects (name, description, user_id) VALUES ('CMS Project 13', 'CMS system for managing business operations', 10);
INSERT INTO projects (name, description, user_id) VALUES ('CRM Project 14', 'CRM system for managing workflows', 5);
INSERT INTO projects (name, description, user_id) VALUES ('E-commerce Project 15', 'E-commerce system for managing workflows', 34);
INSERT INTO projects (name, description, user_id) VALUES ('Automation Project 16', 'Automation system for managing transactions', 29);
INSERT INTO projects (name, description, user_id) VALUES ('Monitoring Project 17', 'Monitoring system for managing customer data', 50);
INSERT INTO projects (name, description, user_id) VALUES ('CRM Project 18', 'CRM system for managing customer data', 14);
INSERT INTO projects (name, description, user_id) VALUES ('ERP Project 19', 'ERP system for managing analytics', 42);
INSERT INTO projects (name, description, user_id) VALUES ('Integration Project 20', 'Integration system for managing user engagement', 2);
INSERT INTO projects (name, description, user_id) VALUES ('Dashboard Project 21', 'Dashboard system for managing analytics', 18);
INSERT INTO projects (name, description, user_id) VALUES ('Portal Project 22', 'Portal system for managing business operations', 17);
INSERT INTO projects (name, description, user_id) VALUES ('Dashboard Project 23', 'Dashboard system for managing transactions', 18);
INSERT INTO projects (name, description, user_id) VALUES ('ERP Project 24', 'ERP system for managing customer data', 18);
INSERT INTO projects (name, description, user_id) VALUES ('Marketplace Project 25', 'Marketplace system for managing customer data', 47);
INSERT INTO projects (name, description, user_id) VALUES ('Dashboard Project 26', 'Dashboard system for managing workflows', 37);
INSERT INTO projects (name, description, user_id) VALUES ('Integration Project 27', 'Integration system for managing transactions', 19);
INSERT INTO projects (name, description, user_id) VALUES ('Messaging Project 28', 'Messaging system for managing transactions', 14);
INSERT INTO projects (name, description, user_id) VALUES ('Integration Project 29', 'Integration system for managing user engagement', 32);
INSERT INTO projects (name, description, user_id) VALUES ('Social Project 30', 'Social system for managing transactions', 31);

-- Insert Applications
INSERT INTO applications ( name, description, appteam_id, project_id) VALUES ( 'Automation Analyzer 1', 'Analyzer service built with Node.js for Automation Project 16. Handles authentication', 11, 16);
INSERT INTO applications ( name, description, appteam_id, project_id) VALUES ( 'Integration Worker 2', 'Worker service built with Python for Integration Project 27. Handles webhooks', 1, 27);
INSERT INTO applications ( name, description, appteam_id, project_id) VALUES ( 'Monitoring Monitor 3', 'Monitor service built with Ruby for Monitoring Project 17. Handles notifications', 6, 17);
INSERT INTO applications ( name, description, appteam_id, project_id) VALUES ( 'Integration Engine 4', 'Engine service built with React for Integration Project 20. Handles reporting', 14, 20);
INSERT INTO applications ( name, description, appteam_id, project_id) VALUES ( 'Integration Controller 5', 'Controller service built with Angular for Integration Project 20. Handles reporting', 2, 20);
INSERT INTO applications ( name, description, appteam_id, project_id) VALUES ( 'CRM Tracker 6', 'Tracker service built with .NET for CRM Project 14. Handles webhooks', 7, 14);
INSERT INTO applications ( name, description, appteam_id, project_id) VALUES ( 'Integration Generator 7', 'Generator service built with Ruby for Integration Project 29. Handles notifications', 18, 29);
INSERT INTO applications ( name, description, appteam_id, project_id) VALUES ( 'Social Tracker 8', 'Tracker service built with Vue for Social Project 30. Handles notifications', 19, 30);
INSERT INTO applications ( name, description, appteam_id, project_id) VALUES ( 'Marketplace Handler 9', 'Handler service built with Node.js for Marketplace Project 9. Handles data processing', 18, 9);
INSERT INTO applications ( name, description, appteam_id, project_id) VALUES ('Automation Generator 10', 'Generator service built with Angular for Automation Project 1. Handles reporting', 15, 1);
INSERT INTO applications ( name, description, appteam_id, project_id) VALUES ('Automation Service 11', 'Service service built with Angular for Automation Project 16. Handles integrations', 3, 16);
INSERT INTO applications ( name, description, appteam_id, project_id) VALUES ('Portal Generator 12', 'Generator service built with Vue for Portal Project 22. Handles reporting', 5, 22);
INSERT INTO applications ( name, description, appteam_id, project_id) VALUES ('E-commerce Validator 13', 'Validator service built with C# for E-commerce Project 15. Handles file uploads', 20, 15);
INSERT INTO applications ( name, description, appteam_id, project_id) VALUES ('Integration API 14', 'API service built with Angular for Integration Project 6. Handles payments', 18, 6);
INSERT INTO applications ( name, description, appteam_id, project_id) VALUES ('Monitoring Manager 15', 'Manager service built with Vue for Monitoring Project 17. Handles notifications', 16, 17);
INSERT INTO applications ( name, description, appteam_id, project_id) VALUES ('CRM Controller 16', 'Controller service built with Ruby for CRM Project 18. Handles webhooks', 10, 18);
INSERT INTO applications ( name, description, appteam_id, project_id) VALUES ('Dashboard Manager 17', 'Manager service built with Angular for Dashboard Project 26. Handles webhooks', 17, 26);
INSERT INTO applications ( name, description, appteam_id, project_id) VALUES ('CMS Generator 18', 'Generator service built with C# for CMS Project 13. Handles data processing', 17, 13);
INSERT INTO applications ( name, description, appteam_id, project_id) VALUES ('Dashboard Worker 19', 'Worker service built with Python for Dashboard Project 26. Handles webhooks', 15, 26);
INSERT INTO applications ( name, description, appteam_id, project_id) VALUES ('Dashboard Service 20', 'Service service built with PHP for Dashboard Project 26. Handles data processing', 8, 26);
INSERT INTO applications ( name, description, appteam_id, project_id) VALUES ('Marketplace Analyzer 21', 'Analyzer service built with C# for Marketplace Project 25. Handles integrations', 13, 25);
INSERT INTO applications ( name, description, appteam_id, project_id) VALUES ('Dashboard API 22', 'API service built with Node.js for Dashboard Project 23. Handles notifications', 6, 23);
INSERT INTO applications ( name, description, appteam_id, project_id) VALUES ('Automation Engine 23', 'Engine service built with Vue for Automation Project 8. Handles notifications', 9, 8);
INSERT INTO applications ( name, description, appteam_id, project_id) VALUES ('Automation Monitor 24', 'Monitor service built with Java for Automation Project 16. Handles file uploads', 18, 16);
INSERT INTO applications ( name, description, appteam_id, project_id) VALUES ('Integration API 25', 'API service built with PHP for Integration Project 20. Handles payments', 8, 20);
INSERT INTO applications ( name, description, appteam_id, project_id) VALUES ('Analytics Processor 26', 'Processor service built with Angular for Analytics Project 4. Handles file uploads', 8, 4);
INSERT INTO applications ( name, description, appteam_id, project_id) VALUES ('E-commerce Engine 27', 'Engine service built with React for E-commerce Project 15. Handles file uploads', 15, 15);
INSERT INTO applications ( name, description, appteam_id, project_id) VALUES ('ERP Generator 28', 'Generator service built with Java for ERP Project 24. Handles notifications', 16, 24);
INSERT INTO applications ( name, description, appteam_id, project_id) VALUES ('Messaging Generator 29', 'Generator service built with Ruby for Messaging Project 28. Handles data processing', 18, 28);
INSERT INTO applications ( name, description, appteam_id, project_id) VALUES ('ERP Generator 30', 'Generator service built with Vue for ERP Project 19. Handles authentication', 18, 19);
INSERT INTO applications ( name, description, appteam_id, project_id) VALUES ('Automation Validator 31', 'Validator service built with Angular for Automation Project 8. Handles file uploads', 17, 8);
INSERT INTO applications ( name, description, appteam_id, project_id) VALUES ('CMS Engine 32', 'Engine service built with Go for CMS Project 13. Handles reporting', 11, 13);
INSERT INTO applications ( name, description, appteam_id, project_id) VALUES ('Monitoring Manager 33', 'Manager service built with .NET for Monitoring Project 10. Handles payments', 19, 10);
INSERT INTO applications ( name, description, appteam_id, project_id) VALUES ('CRM Scheduler 34', 'Scheduler service built with Java for CRM Project 14. Handles file uploads', 8, 14);
INSERT INTO applications ( name, description, appteam_id, project_id) VALUES ('CRM Controller 35', 'Controller service built with C# for CRM Project 14. Handles file uploads', 13, 14);
INSERT INTO applications ( name, description, appteam_id, project_id) VALUES ('Portal Manager 36', 'Manager service built with C# for Portal Project 22. Handles webhooks', 12, 22);
INSERT INTO applications ( name, description, appteam_id, project_id) VALUES ('Analytics Scheduler 37', 'Scheduler service built with React for Analytics Project 5. Handles reporting', 5, 5);
INSERT INTO applications ( name, description, appteam_id, project_id) VALUES ('Automation Analyzer 38', 'Analyzer service built with Ruby for Automation Project 1. Handles notifications', 18, 1);
INSERT INTO applications ( name, description, appteam_id, project_id) VALUES ('Marketplace Service 39', 'Service service built with Vue for Marketplace Project 9. Handles reporting', 4, 9);
INSERT INTO applications ( name, description, appteam_id, project_id) VALUES ('Monitoring Engine 40', 'Engine service built with PHP for Monitoring Project 10. Handles payments', 19, 10);
INSERT INTO applications ( name, description, appteam_id, project_id) VALUES ('CRM Service 41', 'Service service built with .NET for CRM Project 18. Handles notifications', 16, 18);
INSERT INTO applications ( name, description, appteam_id, project_id) VALUES ('E-commerce Service 42', 'Service service built with PHP for E-commerce Project 15. Handles webhooks', 6, 15);
INSERT INTO applications ( name, description, appteam_id, project_id) VALUES ('CRM Handler 43', 'Handler service built with .NET for CRM Project 18. Handles notifications', 19, 18);
INSERT INTO applications ( name, description, appteam_id, project_id) VALUES ('Messaging Tracker 44', 'Tracker service built with React for Messaging Project 11. Handles notifications', 19, 11);
INSERT INTO applications ( name, description, appteam_id, project_id) VALUES ('Automation Generator 45', 'Generator service built with C# for Automation Project 8. Handles integrations', 7, 8);
INSERT INTO applications ( name, description, appteam_id, project_id) VALUES ('ERP Manager 46', 'Manager service built with PHP for ERP Project 24. Handles data processing', 11, 24);
INSERT INTO applications ( name, description, appteam_id, project_id) VALUES ('Messaging Engine 47', 'Engine service built with React for Messaging Project 11. Handles payments', 3, 11);
INSERT INTO applications ( name, description, appteam_id, project_id) VALUES ('Integration Processor 48', 'Processor service built with Vue for Integration Project 6. Handles file uploads', 12, 6);
INSERT INTO applications ( name, description, appteam_id, project_id) VALUES ('Dashboard Monitor 49', 'Monitor service built with React for Dashboard Project 21. Handles notifications', 10, 21);
INSERT INTO applications ( name, description, appteam_id, project_id) VALUES ('E-commerce Manager 50', 'Manager service built with React for E-commerce Project 15. Handles webhooks', 4, 15);
INSERT INTO applications ( name, description, appteam_id, project_id) VALUES ('Integration Service 51', 'Service service built with Go for Integration Project 27. Handles webhooks', 16, 27);
INSERT INTO applications ( name, description, appteam_id, project_id) VALUES ('Automation Processor 52', 'Processor service built with Java for Automation Project 3. Handles notifications', 12, 3);
INSERT INTO applications ( name, description, appteam_id, project_id) VALUES ('Integration Tracker 53', 'Tracker service built with Go for Integration Project 27. Handles integrations', 8, 27);
INSERT INTO applications ( name, description, appteam_id, project_id) VALUES ('Automation Service 54', 'Service service built with C# for Automation Project 8. Handles reporting', 12, 8);
INSERT INTO applications ( name, description, appteam_id, project_id) VALUES ('Monitoring Processor 55', 'Processor service built with Go for Monitoring Project 17. Handles notifications', 18, 17);
INSERT INTO applications ( name, description, appteam_id, project_id) VALUES ('Automation Service 56', 'Service service built with .NET for Automation Project 16. Handles webhooks', 15, 16);
INSERT INTO applications ( name, description, appteam_id, project_id) VALUES ('Monitoring Service 57', 'Service service built with Go for Monitoring Project 17. Handles webhooks', 19, 17);
INSERT INTO applications ( name, description, appteam_id, project_id) VALUES ('ERP Handler 58', 'Handler service built with PHP for ERP Project 7. Handles webhooks', 16, 7);
INSERT INTO applications ( name, description, appteam_id, project_id) VALUES ('Automation Validator 59', 'Validator service built with C# for Automation Project 2. Handles webhooks', 18, 2);
INSERT INTO applications ( name, description, appteam_id, project_id) VALUES ('Automation Tracker 60', 'Tracker service built with Node.js for Automation Project 16. Handles authentication', 12, 16);
INSERT INTO applications ( name, description, appteam_id, project_id) VALUES ('Integration Tracker 61', 'Tracker service built with PHP for Integration Project 6. Handles notifications', 8, 6);
INSERT INTO applications ( name, description, appteam_id, project_id) VALUES ('Messaging Generator 62', 'Generator service built with React for Messaging Project 11. Handles authentication', 8, 11);
INSERT INTO applications ( name, description, appteam_id, project_id) VALUES ('ERP Monitor 63', 'Monitor service built with Java for ERP Project 19. Handles reporting', 4, 19);
INSERT INTO applications ( name, description, appteam_id, project_id) VALUES ('Social Scheduler 64', 'Scheduler service built with Go for Social Project 30. Handles reporting', 2, 30);
INSERT INTO applications ( name, description, appteam_id, project_id) VALUES ('E-commerce Validator 65', 'Validator service built with Go for E-commerce Project 15. Handles reporting', 18, 15);
INSERT INTO applications ( name, description, appteam_id, project_id) VALUES ('E-commerce Analyzer 66', 'Analyzer service built with Python for E-commerce Project 15. Handles data processing', 7, 15);
INSERT INTO applications ( name, description, appteam_id, project_id) VALUES ('Messaging Analyzer 67', 'Analyzer service built with Ruby for Messaging Project 11. Handles authentication', 15, 11);
INSERT INTO applications ( name, description, appteam_id, project_id) VALUES ('Monitoring API 68', 'API service built with Java for Monitoring Project 10. Handles authentication', 10, 10);
INSERT INTO applications ( name, description, appteam_id, project_id) VALUES ('ERP Tracker 69', 'Tracker service built with C# for ERP Project 7. Handles authentication', 12, 7);
INSERT INTO applications ( name, description, appteam_id, project_id) VALUES ('Portal API 70', 'API service built with .NET for Portal Project 22. Handles notifications', 18, 22);
INSERT INTO applications ( name, description, appteam_id, project_id) VALUES ('Social Generator 71', 'Generator service built with Python for Social Project 30. Handles integrations', 16, 30);
INSERT INTO applications ( name, description, appteam_id, project_id) VALUES ('Marketplace Scheduler 72', 'Scheduler service built with Angular for Marketplace Project 9. Handles file uploads', 5, 9);
INSERT INTO applications ( name, description, appteam_id, project_id) VALUES ('Monitoring Analyzer 73', 'Analyzer service built with Ruby for Monitoring Project 10. Handles webhooks', 18, 10);
INSERT INTO applications ( name, description, appteam_id, project_id) VALUES ('Automation Validator 74', 'Validator service built with C# for Automation Project 8. Handles file uploads', 19, 8);
INSERT INTO applications ( name, description, appteam_id, project_id) VALUES ('Marketplace Processor 75', 'Processor service built with C# for Marketplace Project 9. Handles integrations', 9, 9);
INSERT INTO applications ( name, description, appteam_id, project_id) VALUES ('CMS Analyzer 76', 'Analyzer service built with Vue for CMS Project 13. Handles integrations', 8, 13);
INSERT INTO applications ( name, description, appteam_id, project_id) VALUES ('Automation Processor 77', 'Processor service built with Angular for Automation Project 2. Handles notifications', 9, 2);
INSERT INTO applications ( name, description, appteam_id, project_id) VALUES ('Dashboard Generator 78', 'Generator service built with React for Dashboard Project 21. Handles data processing', 19, 21);
INSERT INTO applications ( name, description, appteam_id, project_id) VALUES ('Automation Processor 79', 'Processor service built with Ruby for Automation Project 8. Handles file uploads', 16, 8);
INSERT INTO applications ( name, description, appteam_id, project_id) VALUES ('E-commerce Engine 80', 'Engine service built with PHP for E-commerce Project 15. Handles integrations', 1, 15);
INSERT INTO applications ( name, description, appteam_id, project_id) VALUES ('ERP Monitor 81', 'Monitor service built with Angular for ERP Project 7. Handles file uploads', 7, 7);
INSERT INTO applications ( name, description, appteam_id, project_id) VALUES ('Dashboard Handler 82', 'Handler service built with C# for Dashboard Project 21. Handles notifications', 1, 21);
INSERT INTO applications ( name, description, appteam_id, project_id) VALUES ('ERP Controller 83', 'Controller service built with Vue for ERP Project 24. Handles webhooks', 13, 24);
INSERT INTO applications ( name, description, appteam_id, project_id) VALUES ('Integration API 84', 'API service built with React for Integration Project 6. Handles payments', 1, 6);
INSERT INTO applications ( name, description, appteam_id, project_id) VALUES ('Marketplace Worker 85', 'Worker service built with .NET for Marketplace Project 25. Handles authentication', 11, 25);
INSERT INTO applications ( name, description, appteam_id, project_id) VALUES ('CRM Tracker 86', 'Tracker service built with Angular for CRM Project 14. Handles data processing', 15, 14);
INSERT INTO applications ( name, description, appteam_id, project_id) VALUES ('Automation Validator 87', 'Validator service built with Go for Automation Project 2. Handles notifications', 1, 2);
INSERT INTO applications ( name, description, appteam_id, project_id) VALUES ('Integration Worker 88', 'Worker service built with React for Integration Project 27. Handles authentication', 8, 27);
INSERT INTO applications ( name, description, appteam_id, project_id) VALUES ('Portal Generator 89', 'Generator service built with Node.js for Portal Project 22. Handles payments', 14, 22);
INSERT INTO applications ( name, description, appteam_id, project_id) VALUES ('CMS Worker 90', 'Worker service built with C# for CMS Project 13. Handles webhooks', 12, 13);
INSERT INTO applications ( name, description, appteam_id, project_id) VALUES ('Monitoring Processor 91', 'Processor service built with C# for Monitoring Project 10. Handles webhooks', 12, 10);
INSERT INTO applications ( name, description, appteam_id, project_id) VALUES ('Marketplace Handler 92', 'Handler service built with Vue for Marketplace Project 25. Handles file uploads', 16, 25);
INSERT INTO applications ( name, description, appteam_id, project_id) VALUES ('Automation Tracker 93', 'Tracker service built with Java for Automation Project 1. Handles authentication', 18, 1);
INSERT INTO applications ( name, description, appteam_id, project_id) VALUES ('Integration API 94', 'API service built with PHP for Integration Project 27. Handles data processing', 13, 27);
INSERT INTO applications ( name, description, appteam_id, project_id) VALUES ('Integration Engine 95', 'Engine service built with C# for Integration Project 6. Handles notifications', 3, 6);
INSERT INTO applications ( name, description, appteam_id, project_id) VALUES ('Automation Scheduler 96', 'Scheduler service built with Ruby for Automation Project 8. Handles notifications', 20, 8);
INSERT INTO applications ( name, description, appteam_id, project_id) VALUES ('Monitoring API 97', 'API service built with Node.js for Monitoring Project 10. Handles payments', 17, 10);
INSERT INTO applications ( name, description, appteam_id, project_id) VALUES ('ERP Handler 98', 'Handler service built with Angular for ERP Project 19. Handles payments', 10, 19);
INSERT INTO applications ( name, description, appteam_id, project_id) VALUES ('Automation Analyzer 99', 'Analyzer service built with Go for Automation Project 8. Handles notifications', 11, 8);
INSERT INTO applications ( name, description, appteam_id, project_id) VALUES ('CRM Generator 100', 'Generator service built with Go for CRM Project 18. Handles reporting', 2, 18);

-- Insert AppTeam-User relationships
INSERT INTO appteams_users (appteam_id, user_id) VALUES (1, 44);
INSERT INTO appteams_users (appteam_id, user_id) VALUES (1, 43);
INSERT INTO appteams_users (appteam_id, user_id) VALUES (1, 1);
INSERT INTO appteams_users (appteam_id, user_id) VALUES (1, 26);
INSERT INTO appteams_users (appteam_id, user_id) VALUES (1, 49);
INSERT INTO appteams_users (appteam_id, user_id) VALUES (2, 13);
INSERT INTO appteams_users (appteam_id, user_id) VALUES (2, 43);
INSERT INTO appteams_users (appteam_id, user_id) VALUES (3, 30);
INSERT INTO appteams_users (appteam_id, user_id) VALUES (3, 10);
INSERT INTO appteams_users (appteam_id, user_id) VALUES (3, 21);
INSERT INTO appteams_users (appteam_id, user_id) VALUES (3, 42);
INSERT INTO appteams_users (appteam_id, user_id) VALUES (3, 13);
INSERT INTO appteams_users (appteam_id, user_id) VALUES (4, 36);
INSERT INTO appteams_users (appteam_id, user_id) VALUES (4, 22);
INSERT INTO appteams_users (appteam_id, user_id) VALUES (4, 14);
INSERT INTO appteams_users (appteam_id, user_id) VALUES (4, 28);
INSERT INTO appteams_users (appteam_id, user_id) VALUES (4, 44);
INSERT INTO appteams_users (appteam_id, user_id) VALUES (4, 10);
INSERT INTO appteams_users (appteam_id, user_id) VALUES (4, 50);
INSERT INTO appteams_users (appteam_id, user_id) VALUES (4, 29);
INSERT INTO appteams_users (appteam_id, user_id) VALUES (5, 41);
INSERT INTO appteams_users (appteam_id, user_id) VALUES (5, 25);
INSERT INTO appteams_users (appteam_id, user_id) VALUES (5, 30);
INSERT INTO appteams_users (appteam_id, user_id) VALUES (6, 15);
INSERT INTO appteams_users (appteam_id, user_id) VALUES (6, 29);
INSERT INTO appteams_users (appteam_id, user_id) VALUES (6, 41);
INSERT INTO appteams_users (appteam_id, user_id) VALUES (6, 27);
INSERT INTO appteams_users (appteam_id, user_id) VALUES (6, 49);
INSERT INTO appteams_users (appteam_id, user_id) VALUES (6, 28);
INSERT INTO appteams_users (appteam_id, user_id) VALUES (6, 50);
INSERT INTO appteams_users (appteam_id, user_id) VALUES (7, 25);
INSERT INTO appteams_users (appteam_id, user_id) VALUES (7, 1);
INSERT INTO appteams_users (appteam_id, user_id) VALUES (7, 42);
INSERT INTO appteams_users (appteam_id, user_id) VALUES (7, 32);
INSERT INTO appteams_users (appteam_id, user_id) VALUES (7, 24);
INSERT INTO appteams_users (appteam_id, user_id) VALUES (7, 15);
INSERT INTO appteams_users (appteam_id, user_id) VALUES (7, 23);
INSERT INTO appteams_users (appteam_id, user_id) VALUES (7, 16);
INSERT INTO appteams_users (appteam_id, user_id) VALUES (8, 5);
INSERT INTO appteams_users (appteam_id, user_id) VALUES (8, 38);
INSERT INTO appteams_users (appteam_id, user_id) VALUES (8, 4);
INSERT INTO appteams_users (appteam_id, user_id) VALUES (8, 49);
INSERT INTO appteams_users (appteam_id, user_id) VALUES (8, 14);
INSERT INTO appteams_users (appteam_id, user_id) VALUES (8, 16);
INSERT INTO appteams_users (appteam_id, user_id) VALUES (8, 8);
INSERT INTO appteams_users (appteam_id, user_id) VALUES (8, 10);
INSERT INTO appteams_users (appteam_id, user_id) VALUES (9, 15);
INSERT INTO appteams_users (appteam_id, user_id) VALUES (9, 23);
INSERT INTO appteams_users (appteam_id, user_id) VALUES (9, 50);
INSERT INTO appteams_users (appteam_id, user_id) VALUES (10, 19);
INSERT INTO appteams_users (appteam_id, user_id) VALUES (10, 49);
INSERT INTO appteams_users (appteam_id, user_id) VALUES (10, 26);
INSERT INTO appteams_users (appteam_id, user_id) VALUES (10, 4);
INSERT INTO appteams_users (appteam_id, user_id) VALUES (10, 3);
INSERT INTO appteams_users (appteam_id, user_id) VALUES (11, 1);
INSERT INTO appteams_users (appteam_id, user_id) VALUES (11, 14);
INSERT INTO appteams_users (appteam_id, user_id) VALUES (11, 7);
INSERT INTO appteams_users (appteam_id, user_id) VALUES (11, 20);
INSERT INTO appteams_users (appteam_id, user_id) VALUES (11, 36);
INSERT INTO appteams_users (appteam_id, user_id) VALUES (11, 44);
INSERT INTO appteams_users (appteam_id, user_id) VALUES (11, 29);
INSERT INTO appteams_users (appteam_id, user_id) VALUES (12, 50);
INSERT INTO appteams_users (appteam_id, user_id) VALUES (12, 35);
INSERT INTO appteams_users (appteam_id, user_id) VALUES (12, 34);
INSERT INTO appteams_users (appteam_id, user_id) VALUES (12, 41);
INSERT INTO appteams_users (appteam_id, user_id) VALUES (12, 8);
INSERT INTO appteams_users (appteam_id, user_id) VALUES (12, 22);
INSERT INTO appteams_users (appteam_id, user_id) VALUES (13, 12);
INSERT INTO appteams_users (appteam_id, user_id) VALUES (13, 13);
INSERT INTO appteams_users (appteam_id, user_id) VALUES (14, 27);
INSERT INTO appteams_users (appteam_id, user_id) VALUES (14, 44);
INSERT INTO appteams_users (appteam_id, user_id) VALUES (14, 4);
INSERT INTO appteams_users (appteam_id, user_id) VALUES (15, 26);
INSERT INTO appteams_users (appteam_id, user_id) VALUES (15, 32);
INSERT INTO appteams_users (appteam_id, user_id) VALUES (15, 25);
INSERT INTO appteams_users (appteam_id, user_id) VALUES (16, 30);
INSERT INTO appteams_users (appteam_id, user_id) VALUES (16, 26);
INSERT INTO appteams_users (appteam_id, user_id) VALUES (16, 37);
INSERT INTO appteams_users (appteam_id, user_id) VALUES (17, 43);
INSERT INTO appteams_users (appteam_id, user_id) VALUES (17, 4);
INSERT INTO appteams_users (appteam_id, user_id) VALUES (17, 28);
INSERT INTO appteams_users (appteam_id, user_id) VALUES (18, 6);
INSERT INTO appteams_users (appteam_id, user_id) VALUES (18, 21);
INSERT INTO appteams_users (appteam_id, user_id) VALUES (18, 10);
INSERT INTO appteams_users (appteam_id, user_id) VALUES (18, 24);
INSERT INTO appteams_users (appteam_id, user_id) VALUES (18, 12);
INSERT INTO appteams_users (appteam_id, user_id) VALUES (18, 3);
INSERT INTO appteams_users (appteam_id, user_id) VALUES (18, 27);
INSERT INTO appteams_users (appteam_id, user_id) VALUES (18, 17);
INSERT INTO appteams_users (appteam_id, user_id) VALUES (19, 18);
INSERT INTO appteams_users (appteam_id, user_id) VALUES (19, 50);
INSERT INTO appteams_users (appteam_id, user_id) VALUES (19, 19);
INSERT INTO appteams_users (appteam_id, user_id) VALUES (19, 36);
INSERT INTO appteams_users (appteam_id, user_id) VALUES (19, 21);
INSERT INTO appteams_users (appteam_id, user_id) VALUES (19, 10);
INSERT INTO appteams_users (appteam_id, user_id) VALUES (20, 30);
INSERT INTO appteams_users (appteam_id, user_id) VALUES (20, 49);

-- Verify data
SELECT 'Users' as table_name, COUNT(*) as count FROM users
UNION ALL
SELECT 'AppTeams', COUNT(*) FROM appteams
UNION ALL
SELECT 'Projects', COUNT(*) FROM projects
UNION ALL
SELECT 'Applications', COUNT(*) FROM applications
UNION ALL
SELECT 'Team Members', COUNT(*) FROM appteams_users;
